# Generated by Django 4.1 on 2024-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='image',
            field=models.ImageField(upload_to='trip_images'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
